### ISSUE TITLE
Edit document in office - Chrome

### ISSUE THREAD

**Issue by snofear** [ITHit/WebDAVAjax#1]
I am trying to edit document in office. I get browser dialog to edit document in office or cancel the action. The problem is that after timeout if you do not click any button in dialog it always calls error callback.

Configuration:

- Windows 10
- Chrome
- ITHitWebDAVClient version: 5.17.5482.0

Steps to reproduce the problem:

1. Click on edit document action that calls "MicrosoftOfficeEditDocument" function
`oNs.MicrosoftOfficeEditDocument(data.Meta.WebDavPath, errorCallback);`
2. It opens browser dialog where you can click on open or cancel button but do not click any of them and wait 3s
3. ErrorCallback is triggerd after 3s.
4. Click open in browser dialog and document is successfully opened in office.

I expect that errorCallback is not triggered in this case.

**Comment by VolodymyrLychman** [comment]
Hi,

Thank you for your request. You are right, there is an issue with
MicrosoftEditDocument() and EditDocument() JavaScript functions in Chrome.
We have fixed it and will be publishing an update very soon.


Please submit your requests to our Help & Support Center  here:
https://ithitcorp.atlassian.net/servicedesk/customer/portals
